[package]
name = "prepend_struct"
version = "0.1.0"
authors = ["MasuqaT <occar@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
quote = "1"
proc-macro2 = "1.0"
lazy_static = "1.4"

[dependencies.syn]
version = "1.0"
features = ["full"]
