[package]
name = "prepend_macro"
version = "0.1.0"
authors = ["MasuqaT <occar@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
prepend_struct = { path = "../data_struct" }

[dependencies.syn]
version = "1.0"
features = ["full"]