import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const importMap = {
    "imports": {
        "square": "./module/shapes/square.js",
        "circle": "https://example.com/shapes/circle.js"
    }
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <script type="importmap">{JSON.stringify(importMap)}</script>
        </head>
        <body>
        {children}
        </body>
        </html>
    );
}
