/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Assertion {
    #[serde(rename = "tuple_key")]
    pub tuple_key: Box<models::AssertionTupleKey>,
    #[serde(rename = "expectation")]
    pub expectation: bool,
    #[serde(rename = "contextual_tuples", skip_serializing_if = "Option::is_none")]
    pub contextual_tuples: Option<Vec<models::TupleKey>>,
    /// Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation.
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
}

impl Assertion {
    pub fn new(tuple_key: models::AssertionTupleKey, expectation: bool) -> Assertion {
        Assertion {
            tuple_key: Box::new(tuple_key),
            expectation,
            contextual_tuples: None,
            context: None,
        }
    }
}

