/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckError {
    #[serde(rename = "input_error", skip_serializing_if = "Option::is_none")]
    pub input_error: Option<models::ErrorCode>,
    #[serde(rename = "internal_error", skip_serializing_if = "Option::is_none")]
    pub internal_error: Option<models::InternalErrorCode>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl CheckError {
    pub fn new() -> CheckError {
        CheckError {
            input_error: None,
            internal_error: None,
            message: None,
        }
    }
}

