/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpandRequest {
    #[serde(rename = "tuple_key")]
    pub tuple_key: Box<models::ExpandRequestTupleKey>,
    #[serde(rename = "authorization_model_id", skip_serializing_if = "Option::is_none")]
    pub authorization_model_id: Option<String>,
    #[serde(rename = "consistency", skip_serializing_if = "Option::is_none")]
    pub consistency: Option<models::ConsistencyPreference>,
    #[serde(rename = "contextual_tuples", skip_serializing_if = "Option::is_none")]
    pub contextual_tuples: Option<Box<models::ContextualTupleKeys>>,
}

impl ExpandRequest {
    pub fn new(tuple_key: models::ExpandRequestTupleKey) -> ExpandRequest {
        ExpandRequest {
            tuple_key: Box::new(tuple_key),
            authorization_model_id: None,
            consistency: None,
            contextual_tuples: None,
        }
    }
}

