/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpandRequestTupleKey {
    #[serde(rename = "relation")]
    pub relation: String,
    #[serde(rename = "object")]
    pub object: String,
}

impl ExpandRequestTupleKey {
    pub fn new(relation: String, object: String) -> ExpandRequestTupleKey {
        ExpandRequestTupleKey {
            relation,
            object,
        }
    }
}

