/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadChangesResponse {
    #[serde(rename = "changes")]
    pub changes: Vec<models::TupleChange>,
    /// The continuation token will be identical if there are no new changes.
    #[serde(rename = "continuation_token", skip_serializing_if = "Option::is_none")]
    pub continuation_token: Option<String>,
}

impl ReadChangesResponse {
    pub fn new(changes: Vec<models::TupleChange>) -> ReadChangesResponse {
        ReadChangesResponse {
            changes,
            continuation_token: None,
        }
    }
}

