/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadResponse {
    #[serde(rename = "tuples")]
    pub tuples: Vec<models::Tuple>,
    /// The continuation token will be empty if there are no more tuples.
    #[serde(rename = "continuation_token")]
    pub continuation_token: String,
}

impl ReadResponse {
    pub fn new(tuples: Vec<models::Tuple>, continuation_token: String) -> ReadResponse {
        ReadResponse {
            tuples,
            continuation_token,
        }
    }
}

