/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StreamedListObjectsResponse : The response for a StreamedListObjects RPC.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamedListObjectsResponse {
    #[serde(rename = "object")]
    pub object: String,
}

impl StreamedListObjectsResponse {
    /// The response for a StreamedListObjects RPC.
    pub fn new(object: String) -> StreamedListObjectsResponse {
        StreamedListObjectsResponse {
            object,
        }
    }
}

