/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TupleOperation {
    #[serde(rename = "TUPLE_OPERATION_WRITE")]
    Write,
    #[serde(rename = "TUPLE_OPERATION_DELETE")]
    Delete,

}

impl std::fmt::Display for TupleOperation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Write => write!(f, "TUPLE_OPERATION_WRITE"),
            Self::Delete => write!(f, "TUPLE_OPERATION_DELETE"),
        }
    }
}

impl Default for TupleOperation {
    fn default() -> TupleOperation {
        Self::Write
    }
}

