/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersetTreePeriodDifference {
    #[serde(rename = "base")]
    pub base: Box<models::Node>,
    #[serde(rename = "subtract")]
    pub subtract: Box<models::Node>,
}

impl UsersetTreePeriodDifference {
    pub fn new(base: models::Node, subtract: models::Node) -> UsersetTreePeriodDifference {
        UsersetTreePeriodDifference {
            base: Box::new(base),
            subtract: Box::new(subtract),
        }
    }
}

