/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Usersets {
    #[serde(rename = "child")]
    pub child: Vec<models::Userset>,
}

impl Usersets {
    pub fn new(child: Vec<models::Userset>) -> Usersets {
        Usersets {
            child,
        }
    }
}

