/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodTupleToUserset {
    #[serde(rename = "tupleset")]
    pub tupleset: Box<models::ObjectRelation>,
    #[serde(rename = "computedUserset")]
    pub computed_userset: Box<models::ObjectRelation>,
}

impl V1PeriodTupleToUserset {
    pub fn new(tupleset: models::ObjectRelation, computed_userset: models::ObjectRelation) -> V1PeriodTupleToUserset {
        V1PeriodTupleToUserset {
            tupleset: Box::new(tupleset),
            computed_userset: Box::new(computed_userset),
        }
    }
}

