/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteAuthorizationModelResponse {
    #[serde(rename = "authorization_model_id")]
    pub authorization_model_id: String,
}

impl WriteAuthorizationModelResponse {
    pub fn new(authorization_model_id: String) -> WriteAuthorizationModelResponse {
        WriteAuthorizationModelResponse {
            authorization_model_id,
        }
    }
}

