version: '3.7'

services:
  openapi-generate:
    volumes:
      - ./:/local
    image: openapitools/openapi-generator-cli
    command: generate -i https://raw.githubusercontent.com/openfga/api/main/docs/openapiv2/apidocs.swagger.json      
      -g rust -o /local/openfga-client
      --additional-properties=library=reqwest-trait,packageName=openfga-client,packageVersion=1.0.0
  # docker compose run --rm openfga-migrate
  openfga-migrate:
    networks:
      - openfga
    volumes:
      - openfga:/home/nonroot
    user: nonroot
    image: openfga/openfga
    command: migrate --datastore-engine sqlite --datastore-uri
      'file:/home/nonroot/openfga.db'
  openfga:
    container_name: openfga
    networks:
      - openfga
    ports:
      - 3000:3000
      - 8080:8080
      - 8081:8081
    volumes:
      - openfga:/home/nonroot
    user: nonroot
    image: openfga/openfga
    command: run --datastore-engine sqlite --datastore-uri 'file:/home/nonroot/openfga.db'

networks:
  openfga:

volumes:
  openfga:
